name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Docker build test
        run: docker build -t pungrumpy/react-test -f ./client/Dockerfile.dev ./client
      - name: Docker run test
        run: docker run -e CI=true pungrumpy/react-test npm test
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Docker build images
        run: |
          docker build -t pungrumpy/multi-client ./client
          docker build -t pungrumpy/multi-nginx ./nginx
          docker build -t pungrumpy/multi-server ./server
          docker build -t pungrumpy/multi-worker ./worker
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push image to Docker Hub
        run: |
          docker push pungrumpy/multi-client
          docker push pungrumpy/multi-nginx
          docker push pungrumpy/multi-server
          docker push pungrumpy/multi-worker
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: Multidocker-env
          existing_bucket_name: elasticbeanstalk-ap-northeast-1-204681029744
          region: ap-northeast-1
          version_label: ${{ github.sha }}
          wait_for_deploy: true
          bucket_path: docker-multi
